import Head from "next/head";
import {Menu} from "./Menu";
import style from "../styles/Layout.module.css";
import {useContext} from "react";
import {Context} from "../contexts";

export const Layout = ({children, title}: any) => {
    const {state, dispatch} = useContext(Context);
    let userLogged: boolean = false;
    if (state.user){
        userLogged=state.user.isAutenticated;
        console.log(state.user);
    }

    return (
        <div>
            <Head>
                <title>App {title ? ` | ${title}` : ""}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Menu userLogged={userLogged}/>

            <div className={style.container}>{children}</div>
        </div>
    );
}
